# =====================
# EXTERNAL SECRET — PRODUCTION
# Identique au staging, dans le namespace wordpress.
# =====================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wordpress-db
  namespace: wordpress
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: wordpress-db
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: wordpress-db-password
