{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "mysql.secrets" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  db-password: ZGVtbw==
{{- end }}