wordpress:
    deployment:
        image: wordpress:4.8-apache
        replicaCount: 1
    service:
        type: ClusterIP
        port: 80
    
mysql:
    deployment:
        image: mysql:5.6
        replicaCount: 1
    service:
        type: ClusterIP
        port: 3306
    pvc:
        accessMode: ReadWriteOnce
        storage: 2Gi
        storageClassName: local-path

ingress:
  enabled: true
  className: nginx
  # host sera remplacé dynamiquement depuis CI
  host: ""
  path: /
  tls:
    enabled: false  # mettre true si cert-manager configuré
    secretName: wordpress-tls
