require "yaml"
vagrant_root = File.dirname(File.expand_path(__FILE__))
settings = YAML.load_file "#{vagrant_root}/settings.yaml"

IP_SECTIONS = settings["network"]["control_ip"].match(/^([0-9.]+\.)([^.]+)$/)
IP_NW = IP_SECTIONS.captures[0]
IP_START = Integer(IP_SECTIONS.captures[1])
NUM_WORKER_NODES = settings["nodes"]["workers"]["count"]

Vagrant.configure("2") do |config|
  # /etc/hosts setup
  config.vm.provision "shell", env: { "IP_NW" => IP_NW, "IP_START" => IP_START, "NUM_WORKER_NODES" => NUM_WORKER_NODES }, inline: <<-SHELL
    apt-get update -y
    echo "$IP_NW$((IP_START)) controlplane" >> /etc/hosts
    for i in `seq 1 ${NUM_WORKER_NODES}`; do
      echo "$IP_NW$((IP_START+i)) node0${i}" >> /etc/hosts
    done
  SHELL

  # Box selection
  if `uname -m`.strip == "aarch64"
    config.vm.box = settings["software"]["box"] + "-arm64"
  else
    config.vm.box = settings["software"]["box"]
  end
  config.vm.box_check_update = true

  # --- Control Plane ---
  config.vm.define "master" do |controlplane|
    controlplane.vm.hostname = "master"
    controlplane.vm.network "private_network", ip: settings["network"]["control_ip"]

    if settings["shared_folders"]
      settings["shared_folders"].each do |shared_folder|
        controlplane.vm.synced_folder shared_folder["host_path"], shared_folder["vm_path"]
      end
    end

    controlplane.vm.provider "virtualbox" do |vb|
      vb.cpus = settings["nodes"]["control"]["cpu"]
      vb.memory = settings["nodes"]["control"]["memory"]
      if settings["cluster_name"] && settings["cluster_name"] != ""
        vb.customize ["modifyvm", :id, "--groups", "/" + settings["cluster_name"]]
      end
    end

    # Provisioning master
    controlplane.vm.provision "shell",
      env: {
        "DNS_SERVERS" => settings["network"]["dns_servers"].join(" "),
        "ENVIRONMENT" => settings["environment"],
        "KUBERNETES_VERSION" => settings["software"]["kubernetes"],
        "KUBERNETES_VERSION_SHORT" => settings["software"]["kubernetes"][0..3],
        "OS" => settings["software"]["os"]
      },
      path: "scripts/common.sh"

    controlplane.vm.provision "shell",
      env: {
        "CALICO_VERSION" => settings["software"]["calico"],
        "CONTROL_IP" => settings["network"]["control_ip"],
        "POD_CIDR" => settings["network"]["pod_cidr"],
        "SERVICE_CIDR" => settings["network"]["service_cidr"]
      },
      path: "scripts/master.sh"
  end

  # --- Worker Nodes ---
  (1..NUM_WORKER_NODES).each do |i|
    config.vm.define "noeud0#{i}" do |node|
      node.vm.hostname = "noeud0#{i}"
      node.vm.network "private_network", ip: IP_NW + "#{IP_START + i}"

      if settings["shared_folders"]
        settings["shared_folders"].each do |shared_folder|
          node.vm.synced_folder shared_folder["host_path"], shared_folder["vm_path"]
        end
      end

      node.vm.provider "virtualbox" do |vb|
        vb.cpus = settings["nodes"]["workers"]["cpu"]
        vb.memory = settings["nodes"]["workers"]["memory"]
        if settings["cluster_name"] && settings["cluster_name"] != ""
          vb.customize ["modifyvm", :id, "--groups", "/" + settings["cluster_name"]]
        end
      end

      node.vm.provision "shell",
        env: {
          "DNS_SERVERS" => settings["network"]["dns_servers"].join(" "),
          "ENVIRONMENT" => settings["environment"],
          "KUBERNETES_VERSION" => settings["software"]["kubernetes"],
          "KUBERNETES_VERSION_SHORT" => settings["software"]["kubernetes"][0..3],
          "OS" => settings["software"]["os"]
        },
        path: "scripts/common.sh"

      node.vm.provision "shell", path: "scripts/node.sh"
    end
  end

  # --- GitLab Runner ---
  config.vm.define "runner" do |gitlabrunner|
    gitlabrunner.vm.hostname = "runner"
    gitlabrunner.vm.network "private_network", ip: settings["network"]["runner_ip"]

    gitlabrunner.vm.provider "virtualbox" do |vb|
      vb.cpus = settings["nodes"]["workers"]["cpu"]
      vb.memory = settings["nodes"]["workers"]["memory"]
    end

    gitlabrunner.vm.provision "shell",
      env: {
        "DNS_SERVERS" => settings["network"]["dns_servers"].join(" "),
        "ENVIRONMENT" => settings["environment"],
        "OS" => settings["software"]["os"]
      },
      path: "scripts/runner.sh"
  end

  config.vm.define "velero" do |velero|
  velero.vm.box = "ubuntu/jammy64"
  velero.vm.hostname = "velero"

  # Réseau privé
  velero.vm.network "private_network", ip: settings["network"]["velero-backup"]

  # Ressources
  velero.vm.provider "virtualbox" do |vb|
    vb.name = "velero"
    vb.memory = 2048
    vb.cpus = 2
  end

  # Provisionnement via script externe
  velero.vm.provision "shell", path: "velero/provisionner-velero.sh"
end

end
