---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-local-demo-mysql-secrets
  namespace: wordpress
spec:
  encryptedData:
    db-password: AgAq7i9ZrouwdIOPFL9BHcSiSryhyux6IZQKAgUMLR5IuOWaYgeMu7C8daIKWoWrjkT2dG3K7Ut3xw0SSJi1dpHwDQs0+68FtrwXBkkfPWGcJgIX+0U2XyULAxUi5jNzgHL/cj8v8CJOd22gsLC42kOMGpptxSR3v1MIblV0ys9lgAETwNNLhOVs5ysKqgCPe9o1B4NobrgoNTpMFNqxMD+yj0Y6h/xd0uxTbs6mxShi6pQVqJDzeReVyfqSnXjEEQTzPtfbAlIxy1CNfYFzDZTZn8+4fVZDk7uu6kAamQPxmddEifWCA0KQK2t+WS9/CAJ/LMt8TW9Ogc3mjVAeRZUZFLh4WcMNxyX5pWgk2t+/l1id4frhPkoQy/O7YwvZno6gc3Q0iOzihv6e/YiWZkpXiFMcinXfCZ8MmFa6CsiOG3goOPe/GanGEVY6edQkP6PGu9IM6p30EWLH4eZaGl2nvFtACdp9JAefw31TPwAq3iwtihzZdHLtpSoOidsOf0rqq3MrhxFBVToKDFmqtBf2UTgadVM3RmjfvI/gRDH9a/1W58U0sToeF06g8crA0TFkMNM+Fb/uDP4j8BCXiaLUQqpFJKf7VY9e1okU5mgh9MtFyrjb4S+xSG+4I+fYECjkzTa8vcbg1RVk3DOkAIJavskcxohX8tEb/y4yWbjNx/cV/m96uVoSxnLHOr1HNB5ILn44v7BHOYak+pkfr0dZKyGUZBcUpf0=
  template:
    metadata:
      name: wordpress-local-demo-mysql-secrets
      namespace: wordpress
