---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-local-demo-mysql-secrets
  namespace: wordpress
spec:
  encryptedData:
    db-password: AgAq7i9ZrouwdIOPFL9BHcSiSryhyux6IZQKAgUMLR5IuOWaYgeMu7C8daIKWoWrjkT2dG3K7Ut3xw0SSJi1dpHwDQs0+68FtrwXBkkfPWGcJgIX+0U2XyULAxUi5jNzgHL/cj8v8CJOd22gsLC42kOMGpptxSR3v1MIblV0ys9lgAETwNNLhOVs5ysKqgCPe9o1B4NobrgoNTpMFNqxMD+yj0Y6h/xd0uxTbs6mxShi6pQVqJDzeReVyfqSnXjEEQTzPtfbAlIxy1CNfYFzDZTZn8+4fVZDk7uu6kAamQPxmddEifWCA0KQK2t+WS9/CAJ/LMt8TW9Ogc3mjVAeRZUZFLh4WcMNxyX5pWgk2t+/l1id4frhPkoQy/O7YwvZno6gc3Q0iOzihv6e/YiWZkpXiFMcinXfCZ8MmFa6CsiOG3goOPe/GanGEVY6edQkP6PGu9IM6p30EWLH4eZaGl2nvFtACdp9JAefw31TPwAq3iwtihzZdHLtpSoOidsOf0rqq3MrhxFBVToKDFmqtBf2UTgadVM3RmjfvI/gRDH9a/1W58U0sToeF06g8crA0TFkMNM+Fb/uDP4j8BCXiaLUQqpFJKf7VY9e1okU5mgh9MtFyrjb4S+xSG+4I+fYECjkzTa8vcbg1RVk3DOkAIJavskcxohX8tEb/y4yWbjNx/cV/m96uVoSxnLHOr1HNB5ILn44v7BHOYak+pkfr0dZKyGUZBcUpf0=
    wp-admin-password: AgBszfpS3zZ8SS/ONlWf52KP6oFFrXAAj4VtL8QSuNl/E8VvNwqvy8TdVtMhLlrErzLXtM6hxByy8JJ2XbQ0rp2djvhhWgchFnSXugR6D8Evs611mmP2Y3/CMdiBOzVOFJjmY9W1AqrU2UEW20xybWERaZTtLpBq9t2FB/R/oVcZgeynnP125lRDj5mRfQQoYwDpFDF9prRhOpgSr7NsGfZT2SWg59aFsxqEj3dDsRrOsMPI8b+mw9kOS+RBQnhuWUp3HA3FIGhj0n0BPIcEWwgzjXI/5DpDk/K36wdTjdC+VFqW2xIKnMbYw8E5y0k3HqMLh3d4bF3I7LSPf2c7fGrNaPZuenrDvvIW6u1zQNasrUh2ELs9QRD4FG7BgmhW4Y4Tjna0IX/8GFMeNzr3eueb6GArqru4MnL7qevREpf7JevyOas6TRW9eP1YDAGtgPvO3hlBbtsbMyPThMGtNcvjn12EediEel8PEb1kLBB/95tixXW7Koss9GDBgcx3HBjHaC3ZVM64QzdCGYVo+NpetVVqdYgmyTfYgbJ1LsGe07zZvF1F8gfpCsyU1kBT3rNtJxC/DhthCM6FoR7zsNUAVLO0DeA+czyHZWaMtdexvZ3G7DAfyElxnWOG+8YpfV4iatY6Q+Ebn2uVUP5gFwHwDlqdeMDv+qT4PISdaF9VgCdw5zzUiQUQkJdARpHJEaWRN6tNouW5Q5ud9oUfN7cA14F/aA==
  template:
    metadata:
      name: wordpress-local-demo-mysql-secrets
      namespace: wordpress
